#16 new ftp normalizer(incomplete)
nansencenter/metanorm pull request #20
Opened 2020-08-21 08:36 UTC by aanersc

There is a new normalizer needed for reading some specific FTP resources. It contains methods for reading those resources in a hardcoded manner.

2020-08-21 08:40 UTC, aanersc commented
@aperrin66 @akorosov 
for the time being, there two methods that are developed completely, "get_time_coverage_start" and "get_time_coverage_end" as well as "match_domain". Please pay attention to these three only for first time review.

after finalizing with @akorosov about the remote sensing aspects, other methods are going to be correct.

2020-08-26 11:53 UTC, aanersc commented
@aperrin66 @akorosov 
New normalizer with its tests are completed in the a188e51 except for geometry and geometry tests. Please review it because this is the final version of this code if there is no problem in your review.

Hint: Needless to say that: we first merge this PR and then go to PR of harvesting (just like what we did for osisaf). SO, please prioritize reviewing this PR at your earliest convenience.

2020-08-26 14:29 UTC, akorosov requested changes
Major problem is that ftp domain alone cannot be used to set metadata. See inline comment.

Second problem is that OOP is not used efficiently. I suggest to make a base `FTPMetadataNormalizer` that can crawl ftp and perform other generic operations. And then make separate children of `FTPMetadataNormalizer` for each of these data sources.

2020-08-26 14:29 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +        return domain_name
This is incorrect. You cannot distinguish platform or instrument only by ftp domain. All of these domains contain huge amount of data from various instruments and platforms.

2020-08-27 05:54 UTC, aanersc commented
> Major problem is that ftp domain alone cannot be used to set metadata. See inline comment.
> 
> Second problem is that OOP is not used efficiently. I suggest to make a base `FTPMetadataNormalizer` that can crawl ftp and perform other generic operations. And then make separate children of `FTPMetadataNormalizer` for each of these data sources.

@akorosov 
Your second problem:
A normalizer that can crawl? Kindly, what do you mean by it? The crawler crawls at the beginning of harvesting process and the normalizer normalizes at the end of it! The crawler and normalizers are separated by ingesters that are between them! No direct connection between them.

The first point and the whole comment:
By the way, this structure is correct because everything is done in a **step by step** manner. First, crawl and then ingest by normalizing it. These functions are written in a way that there is no function which does lots of thing inside it. Instead we have some small and seperate function that are connected together and accomplish a specific task.  What you want, is to only add some functionality in 'get_instrument' or 'get_platform' function in order to distinguish between the several outputs of crawler based on file and address name of ftp which is possible only by changing these two methods only(or any other get_ methods). The reason is that everything is ready for them including file name and its ftp address inside the normalizer.

Kindly any feedback?

2020-08-27 07:26 UTC, aanersc commented
@akorosov 
Based on your recent comment, I have changed the mechanism of get_platform for working with different platforms that are associated with one ftp resource. You can find it in 2d9c39f. Please give me your feedback as soon as possible in order to change the other get_ methods accordingly.

Hint: the part of address that indicates the platform is inclear for and we have to doulbe check it with you.

2020-08-28 12:16 UTC, aanersc commented
@akorosov 
Regarding your recent feedback, I have refactored the ftp normalizer in order to work more comprehensively inside each ftp domain. 

@akorosov @aperrin66 
For this refactor, I put some dictionaries inside each function which **must be review from remote sensing point of view.** These dictionary are named `dict_for_get_...`. These dicrionaries are working with another dictionary that is huge and contant. That huge class dictionary contains the addresses inside each ftp domain.

This new refactor affected `get_platform`, `get_instrument` and `get_dataset_parameters`.  Other ones that are not varying based on different folders of ftp are not involved in this refactor.

Since this commit is a refactor, the tests should not be changed. The only change is the modification in the `ftp_add_and_file_name` field of the test in order to make them more realistic. 
Although it is still needed to be reviewed from remote sensing point of view to correctly map the name of the folder to the appropriate platform, instrument,etc.

@akorosov @aperrin66 
Once again, I kindly insist on reviewing this one at your earliest convenience.

2020-08-31 08:34 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +                                      "GCOM-W": 'GCOM-W1'}  # jaxa
you still distinguish platforms and instruments by FTP domain

2020-08-31 08:45 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +class FTPMetadataNormalizer(BaseMetadataNormalizer):
Making an FTP normalizer is a bit restrictive: what we need is a mechanism to get information from the full URL of a file

2020-08-31 09:19 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                                      "GCOM-W": 'GCOM-W1'}  # jaxa
FTP domain? the keys of this kind of dictionary is the folder name inside the ftp provider. And the key values are the corresponding string that must be sent to pti for proper delivery of instrument or platform etc.

2020-08-31 09:42 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +                domain_name = 'jaxa'
you probably don't need these intermediate names: you can use the literal domain name (like `'ftp.remss.com'`) as a key in the `domain_map` dictionary

2020-08-31 11:50 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                domain_name = 'jaxa'
addressed in **12d5371**

2020-08-31 11:52 UTC, aanersc commented
There is a tiny refactor in 12d5371 based on @aperrin66 review.

2020-08-31 11:53 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +                                      "GCOM-W": 'GCOM-W1'}  # jaxa
yes we talked about it this morning, that's why I marked it as resolved

2020-08-31 11:54 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +    domain_map = {"anon-ftp.ceda.ac.uk": r'esacci|aerosol|biomass|cloud|esacci_terms_and_conditions\.txt|fire|ghg|glaciers|ice_sheets_antarctica|ice_sheets_greenland|lakes|land_cover|ocean_colour|ozo
why is there `esacci_terms_and_conditions\.txt` in there?

2020-08-31 11:54 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +                  "ftp.gportal.jaxa.jp": r'JERS-1|ADEOS-2|MOS-1b|SLATS|CIRC|MOS-1|AQUA|GCOM-C|GCOM-W|GSMaP|ADEOS|GPM|GPMConstellation|TRMM|TRMM_GPMFormat|GCOM-W\.AMSR2|L3\.PRC_10|L3\.SIC_10|L2\.TPW|L
please break these long strings into multiple lines

2020-08-31 11:56 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +    domain_map = {"anon-ftp.ceda.ac.uk": r'esacci|aerosol|biomass|cloud|esacci_terms_and_conditions\.txt|fire|ghg|glaciers|ice_sheets_antarctica|ice_sheets_greenland|lakes|land_cover|ocean_colour|ozo
I systematically copy the names with nlst command of ftp. And this name is forgotten to be removed! I will remove it.

2020-08-31 11:57 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +        pattern = re.compile(self.domain_map[raw_attributes['ftp_domain_name']])
you can store the compiled regular expressions in the dictionary instead of re-compiling it every time

2020-08-31 12:02 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                  "ftp.gportal.jaxa.jp": r'JERS-1|ADEOS-2|MOS-1b|SLATS|CIRC|MOS-1|AQUA|GCOM-C|GCOM-W|GSMaP|ADEOS|GPM|GPMConstellation|TRMM|TRMM_GPMFormat|GCOM-W\.AMSR2|L3\.PRC_10|L3\.SIC_10|L2\.TPW|L
Done in the next commit

2020-08-31 12:08 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +        return [x for x in pattern.findall(str(raw_attributes['ftp_add_and_file_name'].split('/'))) if x in associated_dictionary.keys()][0]
Why do you split `raw_attributes['ftp_add_and_file_name']` into a list, and then turn it into a string right after?
You can just use `raw_attributes['ftp_add_and_file_name']` directly.

2020-08-31 12:11 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +        pattern = re.compile(self.domain_map[raw_attributes['ftp_domain_name']])
But each time we need raw_attributes to compile the pattern and it varies based on the input.Where do you want to place this line?

2020-08-31 12:16 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +        if set([self.metadata_name]).issubset(raw_attributes.keys()):
why is `metadata_name` a class attribute? you only use it here

2020-08-31 12:17 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +            if raw_attributes['ftp_domain_name'] in domain_set:
just check that `raw_attributes['ftp_domain_name']` is in `self.domain_map.keys()`

2020-08-31 12:20 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +        if set([self.metadata_name]).issubset(raw_attributes.keys()):
Done in the next commit

2020-08-31 12:25 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +            if raw_attributes['ftp_domain_name'] in domain_set:
Done in the next commit

2020-08-31 12:25 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +    def dictionary_key_finder(self, raw_attributes, associated_dictionary):
I think this method does too much at once. It would probably be more readable if it only extracted the folder names from `raw_attributes['ftp_add_and_file_name']`, and the check to see if it is in `associated_dictionary` can be done in another method, or even in the calling method.

2020-08-31 12:28 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +            if self.match_domain(raw_attributes) == "ftp.remss.com":
We already talked about this kind of thing. Store the result in a variable, don't call the method in each condition

2020-08-31 12:33 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +        pattern = re.compile(self.domain_map[raw_attributes['ftp_domain_name']])
in the global dictionary: for each entry store the compiled regex

2020-08-31 12:34 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +    def dictionary_key_finder(self, raw_attributes, associated_dictionary):
I wrote it this way to make it more generic in order to work with `get_instrument`, `get_platform` and  `get_dataset_parameters`. What exactly do you suggest? split up this generic function?

2020-08-31 13:04 UTC, akorosov requested changes
Simplify logic according to comments.

2020-08-31 13:04 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +        dict_for_get_gcmd_platform = {"esacci": 'Earth Observation Satellites',  # ceda
In my opinion this is too complicated approach as it needs two mappings and regex:
correct_folder_names = domain_map[ftp_domain] (in one place)
platform_name = dict_for_get_gcmd_platform[folder_name] (in another place)

This is hiding the actual mapping between FTP url and actual platform/instrument, etc very deeply. And then it is hard (or even impossible due to ambiguity) to set correct folder names in `dict_for_get_gcmd_platform`. For example, if i set `{'sst': 'Earth Observation Satellites'}` will it work both for anon-ftp.ceda.ac.uk and for ftp.remss.com? I don't know! I have to look through all subdirs of both FTP servers and check which data is inside. I cannot do that.

To simplify I suggest to have only one mapping: instrument = instrument_on_ftp[ftp_basedir]

The simplest way would be to add full urls as keys and short_name of instrument as values:
```python
 instrument_on_ftp = {
    'ftp://ftp.remss.com/gmi/' : 'gmi',
    'ftp://ftp.gportal.jaxa.jp:/standard/GCOM-W/GCOM-W.AMSR2': 'AMSR2'
}
```

Then for each full FTP path of the file to loop over the keys of that mapping and check if they are in the path:
```python
for ftp_base_dir in instrument_on_ftp.keys():
    if ftp_base_dir in  raw_attributes['ftp_full_address']:
        return pti.get_gcmd_platform(instrument_on_ftp[ftp_base_dir])
```
That's it!

And the same for platform and parameters, of course.

As we start with onlthy three products (sst from esa, amsr2 from jaxa, and gmi from remms) these dictionaries will be quite small. As we add more FTP products they will increase but it will be crystal clear what refers to what.

2020-09-01 06:57 UTC, aanersc commented
@aperrin66 @akorosov 
Your approach is applied in **c96995a**. It is ready to be reviewed.

2020-09-01 07:17 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +                return pti.get_gcmd_platform(platform_on_ftp[ftp_base_dir])
This would be much easier if you pass the whole URL to the normalizer (which is already the case if your ingester inherits from `MetanormIngester`).
Then you can just use `raw_attributes['url'].startswith(...)`.
And it will work with any URL.

2020-09-01 09:36 UTC, akorosov requested changes
Please remove `match_domain` and use `raw_attributes['url']` as suggested in the inline comments.

2020-09-01 09:36 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +class FTPMetadataNormalizer(BaseMetadataNormalizer):
```suggestion
class URLMetadataNormalizer(BaseMetadataNormalizer):
```

2020-09-01 09:36 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +    """ Normalizer for hardcoding information for the ftp-derived cases """
```suggestion
    """ Normalizer for hardcoding information based on URLS """
```

2020-09-01 09:36 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                           "ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2": 'GCOM-W1'}  # jaxa
```suggestion
        urls_platforms = {"ftp://ftp.remss.com/gmi": 'GPM',
                           "ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/": 'Earth Observation Satellites',
                           "ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/": 'GCOM-W1'}  # jaxa
```

2020-09-01 09:36 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                return pti.get_gcmd_platform(platform_on_ftp[ftp_base_dir])
```suggestion
        for url in urls_platforms.keys():
            if raw_attributes['url'].startswith(url):
                return pti.get_gcmd_platform(urls_platforms[url])
```

Please repeat that logic for `get_instrument`, `get_provider`, `get_dataset_parameter`, `get_geometry`

2020-09-01 09:36 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +            if match_result == "ftp.remss.com":
```suggestion
        if raw_attributes['url'].startswith('ftp://ftp.remss.com'):
```

2020-09-01 09:36 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +            if match_result == "ftp.remss.com":
Fix also below for other URLs

2020-09-01 09:36 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                return dateutil.parser.parse("19820101T000000").replace(tzinfo=tzutc())+relativedelta(days=+int(raw_attributes['ftp_add_and_file_name'].split('/')[-1][1:4]))
Too long line

2020-09-01 09:36 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                    return dateutil.parser.parse(extracted_date).replace(tzinfo=tzutc())
Largely repeats `get_time_coverage_start`. Revise logic to avoid repetition.

2020-09-01 09:36 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                return raw_attributes['ftp_domain_name']
This will not be used anymore after the suggested changes.
```suggestion
```

2020-09-01 09:36 UTC, akorosov commented on tests/normalizers/test_ftp.py
> +                 'ftp_add_and_file_name': 'gmi/bmaps_v08.2/y2014/m06/f35_201406v8.2.gz'}),
```suggestion
                {'url': 'ftp://ftp.remss.com/gmi/bmaps_v08.2/y2014/m06/f35_201406v8.2.gz'}),
```

Please fix also in all tests below.

2020-09-01 09:36 UTC, akorosov commented on tests/normalizers/test_ftp.py
> +                                or self.normalizer.__getattribute__(function_name)({'ftp_domain_name': 'test_ftp_resource', 'ftp_add_and_file_name': ''}) is None)
Make explicit calls to functions instead of loop.

2020-09-01 09:57 UTC, aanersc commented
a4be9aa concerns this comment of @aperrin66 (https://github.com/nansencenter/metanorm/pull/20#discussion_r480908679) which involves modification ingester as well. From Now on I read the comments of @akorosov and improve it based on that(https://github.com/nansencenter/metanorm/pull/20#pullrequestreview-479549279).

2020-09-01 10:37 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +class FTPMetadataNormalizer(BaseMetadataNormalizer):
Done in the next commit.

2020-09-01 10:38 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +    """ Normalizer for hardcoding information for the ftp-derived cases """
Done in the next commit

2020-09-01 10:43 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                           "ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2": 'GCOM-W1'}  # jaxa
Done in the next commit

2020-09-01 10:46 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                    return dateutil.parser.parse(extracted_date).replace(tzinfo=tzutc())
Largely repeats get_time_coverage_start? What do you mean by it? I don't understand your comment!

2020-09-01 11:15 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +            return None
This method is still hard to read.
Maybe you can store a format string understandable by `datetime.strptime()` in a dictionary in order to achieve a behavior similar to `get_platform()` and `get_instrument()`.

See https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

2020-09-01 11:58 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +            return None
@akorosov @aperrin66 
What is inside these two methods for start and end time are the code for those support materials and calculation (that are stored alongside the files inside the ftp repo). So, I may not change the algorithm(because it is fixed in those ftp support materials), but I try to improve into a more readable one.

2020-09-01 13:05 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                    return dateutil.parser.parse(extracted_date).replace(tzinfo=tzutc())
I mean that, for example, this block:
```python
                extracted_date = ftp_add_and_file_name.split(
                    '/')[-1].split('v')[0].split('_')[1]
                if len(extracted_date) == 6 and extracted_date.startswith('2'):
                    # adding last day of month based on the calendar
                    # as the last day of month for the files that belong to whole month
                    extracted_date += str(calendar.monthrange(
                        int(extracted_date[:4]), int(extracted_date[4:]))[1])
                # 'd3d' cases are the average of three consequent days! so end day is tomorrow!
                # if condition is the search of 'd3d' in the filename
                if 'd3d' in ftp_add_and_file_name.split('/')[-1]:
                    return dateutil.parser.parse(extracted_date).replace(tzinfo=tzutc())+relativedelta(days=+1)
                    # for weekly average ones in the "weeks" folder
                    # if condition is the search of "weeks" folder in the FTP path
                elif "weeks" in ftp_add_and_file_name.split('/'):
                    return dateutil.parser.parse(extracted_date).replace(tzinfo=tzutc())+relativedelta(days=+3)
                else:  # normal cases that are neither being 'd3d' nor inside "week"
                    return dateutil.parser.parse(extracted_date).replace(tzinfo=tzutc())
```
Is almost exactly the same in both `get_time_coverage_start` and `get_time_coverage_end`. Which violates the DRY principle. One solution is to move it to a separate method for extracting datetime and then call this method from both `get_time_coverage_start` and from `get_time_coverage_end`.

2020-09-01 13:22 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                    return dateutil.parser.parse(extracted_date).replace(tzinfo=tzutc())
Yeap! thanks for clarification

2020-09-02 07:15 UTC, aanersc commented on tests/normalizers/test_ftp.py
> +                 'ftp_add_and_file_name': 'gmi/bmaps_v08.2/y2014/m06/f35_201406v8.2.gz'}),
Done in the next commit

2020-09-02 07:15 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                return raw_attributes['ftp_domain_name']
Done in the next commit

2020-09-02 07:36 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                return pti.get_gcmd_platform(platform_on_ftp[ftp_base_dir])
Done in the next commit

2020-09-02 07:37 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +            if match_result == "ftp.remss.com":
Done in the next commit

2020-09-02 07:37 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                return dateutil.parser.parse("19820101T000000").replace(tzinfo=tzutc())+relativedelta(days=+int(raw_attributes['ftp_add_and_file_name'].split('/')[-1][1:4]))
Done in the next commit

2020-09-02 07:37 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                    return dateutil.parser.parse(extracted_date).replace(tzinfo=tzutc())
Done in the next commit

2020-09-02 07:50 UTC, aanersc commented on tests/normalizers/test_ftp.py
> +                                or self.normalizer.__getattribute__(function_name)({'ftp_domain_name': 'test_ftp_resource', 'ftp_add_and_file_name': ''}) is None)
Done in the next commit

2020-09-02 09:48 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +            return None
Done in the next commit

2020-09-02 09:48 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                return pti.get_gcmd_platform(platform_on_ftp[ftp_base_dir])
Done in the next commit

2020-09-02 10:04 UTC, aanersc commented
@akorosov @aperrin66 
All of your comments are addressed in 5583616. The extract workflow is place in the `get_time_coverage_start` method. And the `get_time_coverage_end` uses some modifications of `get_time_coverage_start` to create the correct dates. Putting another function just make the code more complicated in my opinion. In total, the number of lines of code does not warry and it is not beneficial to do it this way or that way. I kindly ask you to review this commit **carefully**.

2020-09-02 12:21 UTC, aanersc commented
@aperrin66 @akorosov 
After running the tests of harvesting repo, I slightly modify the methods in 42e3bff. I have found that this behaviour of this normalizer must be more restricted. Just like the 'subset' statements that is used for the previous ones. in order to work properly in the chain of normalizers.
There is no big change. Only I add one line of presence of 'url' in the raw attribute in order to make this normalizer enable to work.

Like the line 32 in figure below:
![image](https://user-images.githubusercontent.com/62345618/91980382-73c4b480-ed27-11ea-9e6d-cb7e9f06f49f.png)


SO it is not a big change!

2020-09-02 13:01 UTC, aanersc commented
@aperrin66 @akorosov 
6aaffe1: One more test is added in order to prevent the mentioned errors in https://github.com/nansencenter/metanorm/pull/20#issuecomment-685696556

2020-09-02 13:37 UTC, akorosov requested changes
Much better now!
Few modifications are still needed:
* Replace `looper` with `get_matching_value` and simplify / generalize it's usage
* Split too long lines
* Update few URLs in urls_* dictionaries
* Fix `get_time_coverage*` methods
* Let's work with L3 data from JAXA. Fix for some tests is needed.

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +
1. Always name your functions with verb.
2. Avoid repetition
3. Simplify calls to functions
```suggestion
    def get_matching_value(self, associated_dict, raw_attributes, url_function):
        """ Loop through <associated_dict> and get matching value using appropriate function """
        if 'url ' in raw_attributes:
            for url in associated_dict.keys():
                if raw_attributes['url'].startswith(url):
                    return url_function(associated_dict[url])
```

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +        if 'url' in raw_attributes:
Please fix in other methods
```suggestion
```

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +            return self.looper(urls_platforms, raw_attributes['url'], "get_gcmd_platform")
Please fix in other methods
```suggestion
            return self.get_matching_value(urls_platforms, raw_attributes, pti.get_gcmd_platform)
```

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +    def get_time_coverage_start(self, raw_attributes):
`get_time_coverage_start` and `get_time_coverage_end` are not readable and repetitive.
Adding more functions actually makes the code easier.
Please fix according to previous comments.

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                             'ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2': GEOSGeometry(('POLYGON((1 1, 1 2, 2 2, 2 1, 1 1))'), srid=4326),
Too long lines.

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                    return urls_geometry[url]
You can remove `GEOSGeometry()` from dictionary above and replace with:
```suggestion
            return self.get_matching_value(urls_geometry, raw_attributes, GEOSGeometry)
```

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                    return title_map[url]
```suggestion
            return self.get_matching_value(urls_geometry, raw_attributes, str)
```

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +            "ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/data/CDR_v2/Climatology/L4/v2.1":
```suggestion
            "ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/":
```

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                'ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/data/CDR_v2/Climatology/L4/v2.1':
```suggestion
                'ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/':
```

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +            urls_dsp = {'ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/data/CDR_v2/Climatology/L4/v2.1': ['sea_surface_temperature'],
```suggestion
            urls_dsp = {'ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/': ['sea_surface_temperature'],
```

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                        'ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2': ['sea_surface_temperature'],
```suggestion
                        'ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2/L2.SST': ['sea_surface_temperature'],
                        'ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2/L3.SST_10': ['sea_surface_temperature'],
                        'ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2/L3.SST_25': ['sea_surface_temperature'],
```

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +            urls_geometry = {'ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/data/CDR_v2/Climatology/L4/v2.1': GEOSGeometry(('POLYGON((-180 -90, -180 90, 180 90, 180 -90, -180 -90))'), srid=4326),
```suggestion
            urls_geometry = {'ftp://anon-ftp.ceda.ac.uk/neodc/esacci/sst/': GEOSGeometry(('POLYGON((-180 -90, -180 90, 180 90, 180 -90, -180 -90))'), srid=4326),
```

2020-09-02 13:37 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +                             'ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2': GEOSGeometry(('POLYGON((1 1, 1 2, 2 2, 2 1, 1 1))'), srid=4326),
Let's fix it for L3 SST so far.
```suggestion
                             'ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2/L3.SST_10': GEOSGeometry(('POLYGON((-180 -90, -180 90, 180 90, 180 -90, -180 -90))'), srid=4326),
                             'ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2/L3.SST_25': GEOSGeometry(('POLYGON((-180 -90, -180 90, 180 90, 180 -90, -180 -90))'), srid=4326),
```

2020-09-02 13:37 UTC, akorosov commented on tests/normalizers/test_ftp.py
> +                {'url': 'ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2/L2.SST/3/2012/07/GW1AM2_201207031905_134D_L2SGSSTLB3300300.h5'}),
Maybe let's work with L3 data only so far. As long as we are waiting for reply from ODL.

2020-09-03 06:42 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +        if 'url' in raw_attributes:
@akorosov 
Do you mean putting thins line one time in get_matching_value and remove it from other get_... functions?

2020-09-03 08:52 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +        if 'url' in raw_attributes:
Yes, sure.

2020-09-03 08:57 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +                    return url_function(associated_dict[url])
Maybe put an explicit `return None` here, to make it very clear what happens if no match is found.

2020-09-03 09:15 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +        if 'url' in raw_attributes:
That is the wrong algorithm. We need to check at the beginning of each of those `get_..` function to omit what is inside the function and go to the next normalizer if there is no 'url' in the raw_attributes. So, the correct place is at the begging of each of these `get_..` function, instead of inside the `get_matching_value` function. 

If we put in inside `get_matching_value`, then all of these calculation are done and the at then in the end we found that this is the incorrect normalizer! What I say as` in the end` is inside the `get_matching_value` which is called inside the `get__` functon.

Your feedback?

2020-09-03 09:25 UTC, aanersc commented on tests/normalizers/test_ftp.py
> +                {'url': 'ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2/L2.SST/3/2012/07/GW1AM2_201207031905_134D_L2SGSSTLB3300300.h5'}),
Done in the next commit

2020-09-03 09:26 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                             'ftp://ftp.gportal.jaxa.jp/standard/GCOM-W/GCOM-W.AMSR2': GEOSGeometry(('POLYGON((1 1, 1 2, 2 2, 2 1, 1 1))'), srid=4326),
Done in the next commit

2020-09-03 09:26 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +    def get_time_coverage_start(self, raw_attributes):
Done in the next commit

2020-09-03 09:26 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +            return self.looper(urls_platforms, raw_attributes['url'], "get_gcmd_platform")
Done in the next commit

2020-09-03 09:26 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +                    return url_function(associated_dict[url])
Done in the next commit

2020-09-03 09:29 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +        if 'url' in raw_attributes:
It does not really matter because testing that `raw_attributes['url']` is present does not guarantee that you are in the correct normalizer. 
It's testing that the url starts with one of the known prefixes that ensures that, and this part is already done in `get_matching_value()`, so you can put the test on `raw_attributes['url']` in there as well.

2020-09-03 09:37 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +        if 'url' in raw_attributes:
@aperrin66 @akorosov 
But it slows down the normalization process! We first need to check that whether it is present and in the second level of checking (which is implicitly done in the `get_matching_value`) we investigate that is there any suitable starting string for url or not!

As soon as we find out the absence of the 'url' in the raw_attributes, we need to go to next normalizer immediately! Notice that these normalizers are called in a recursice manner one inside another and it is critical to speed up. because recursive calling is very time-consuming and it matters for us to check this aspect first!

Your feedback?

2020-09-03 10:09 UTC, aperrin66 commented on metanorm/normalizers/ftp.py
> +        if 'url' in raw_attributes:
Personally I don't mind either way.
However, normalizers are not recursive; the way they are used is pretty much traversing a linked list.

2020-09-03 10:20 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +        if 'url' in raw_attributes:
@aperrin66 
@akorosov 
They are recursive! Here is my call stack when I debug!
![image](https://user-images.githubusercontent.com/62345618/92102621-2277fc00-eddf-11ea-9262-fe3467bdc7fc.png)

And Here is the same call stack after breakpoint stop the same line:
![image](https://user-images.githubusercontent.com/62345618/92102761-4cc9b980-eddf-11ea-969f-6309f2526200.png)

Pay attention to how many times the normalize function is called in the call stack in the top of call stack! first three times and in the second picture four times! So it is recursive because of this line:
https://github.com/nansencenter/metanorm/blob/d09a2908f8b4487e579c77b3652fc1d44b774bb6/metanorm/normalizers/base.py#L95

2020-09-03 12:09 UTC, aanersc commented
@akorosov 
@aperrin66 
All of your comments are addressed in 578d948 except this one https://github.com/nansencenter/metanorm/pull/20#discussion_r482058863 which I strongly recommend not to do it. Otherwise, tell me to do it.

It is ready to merge I think.

2020-09-03 12:17 UTC, aanersc commented
@akorosov @aperrin66 
There is a tiny mistake in the name of the function that must be changed in order not to get confused with others and as a `get_...` function. It is corrected in 1715e5c

2020-09-03 12:24 UTC, akorosov commented on metanorm/normalizers/ftp.py
> +        if 'url' in raw_attributes:
You are right, assignment of `urls_platforms` is done every time the `get_platform` method is called and this slows down the process. Maybe by 1 microsecond per 1000 records but still slows down. Normally I prefer readability to speed (in reasonable limits, of course). But let's optimise further:
1. Move `urls_platforms` to class attributes
2. Checking `if 'url' in raw_attributes` in `get_matching_value`
3. Refactor:
```python
    def get_platform(self, raw_attributes):
        return self.get_matching_value(self.urls_platforms, raw_attributes['url'], pti.get_gcmd_platform)
```
Then we kill both rabbits with one shot: improve speed and readability.

Is it too much to expect such optimisation from a developer instead of arguing for a rejected solution?

2020-09-04 07:02 UTC, aanersc commented on metanorm/normalizers/ftp.py
> +        if 'url' in raw_attributes:
Done in the next commit.

2020-09-04 07:02 UTC, aanersc commented
@aperrin66 
@akorosov 
All of your comments are addressed in 24e73e3 including the mentioned discussion.

2020-09-04 07:03 UTC, aanersc commented
@aperrin66
@akorosov

It is ready to merge if you agreed with it.

2020-09-04 07:15 UTC, aanersc commented
@aperrin66 
@akorosov 
Only the names and some docstrings are corrected in be4bf63. The code is the same as the previous one.

2020-09-04 12:28 UTC, aanersc commented
@aperrin66 @akorosov 
Harvesting ability of monthfiles of jaxa is added to 96b1ac7.

2020-09-04 14:00 UTC, akorosov requested changes
Better, but still requires changes. Please respect DRY principle and use verbs in function names as suggested.
Also check line lengths and space before and after + and - operators.

2020-09-07 07:02 UTC, aanersc commented on metanorm/normalizers/url.py
> +            return extracted_date
Done in the next commit

2020-09-07 07:04 UTC, aanersc commented
@aperrin66 
@akorosov 
All of your comments are addressed in 54e498f

2020-09-08 07:02 UTC, akorosov requested changes
Few minor things to change. Then it is ready for merging.

2020-09-08 07:02 UTC, akorosov commented on tests/normalizers/test_url.py
> +            datetime(year=1983, month=1, day=1, hour=0, minute=0, second=0, tzinfo=tzutc()))
It is the day 365, should the start be on 31 December?

2020-09-08 07:02 UTC, akorosov commented on tests/normalizers/test_url.py
> +            datetime(year=2011, month=1, day=1, hour=0, minute=0, second=0, tzinfo=tzutc()))
The same here. Shouldn't the end be December 31?

2020-09-08 07:15 UTC, aanersc commented on metanorm/normalizers/url.py
> +                url_time_, raw_attributes, URLMetadataNormalizer.extract_time)
@akorosov 
Theese two are static method and we can a static method inside another static method here. There is no other way to call it because self is meaningless inside static methods. This suggestions results in python error!

2020-09-08 07:19 UTC, aanersc commented on metanorm/normalizers/url.py
> +                return extracted_date+relativedelta(days=+int(file_name[1:4]))
Done in the next commit

2020-09-08 07:23 UTC, aanersc commented on metanorm/normalizers/url.py
> +                    extracted_date = extracted_date+relativedelta(days=d)
I rely on autopep8 up to now to do it. OK, I pay attention from now on!

2020-09-08 07:24 UTC, aanersc commented on tests/normalizers/test_url.py
> +            datetime(year=1983, month=1, day=1, hour=0, minute=0, second=0, tzinfo=tzutc()))
@akorosov 
No. It should be the first year of the next year! And it is! So the logic of the test is correct! The value is 1982 instead of 1983 in the code!

2020-09-08 07:25 UTC, aanersc commented on tests/normalizers/test_url.py
> +            datetime(year=2011, month=1, day=1, hour=0, minute=0, second=0, tzinfo=tzutc()))
No. It should be the first year of the next year! And it is! So the logic of the test is correct! The value is 2010 instead of 2011 in the code!

2020-09-08 07:30 UTC, aanersc commented on metanorm/normalizers/url.py
> +                            extracted_date + URLMetadataNormalizer.length_of_month(extracted_date)
@akorosov 
First we need to make sure the the url belongs to jaxa portal, then we in the next step we need to check that file has that specific condition! If the file comes from somewhere else, then that split method may give an error because it is not garanteed that the files of other ftp servers have '_' inside them.

With this explanation it robust and consistent to uese this multilevel if! right?

2020-09-08 07:51 UTC, aanersc commented on tests/normalizers/test_url.py
> +            datetime(year=2011, month=1, day=1, hour=0, minute=0, second=0, tzinfo=tzutc()))
@akorosov 
Yeah, you are right!

2020-09-08 07:51 UTC, aanersc commented on tests/normalizers/test_url.py
> +            datetime(year=1983, month=1, day=1, hour=0, minute=0, second=0, tzinfo=tzutc()))
@akorosov 
Yeah, you are right!

2020-09-08 07:51 UTC, aanersc commented on tests/normalizers/test_url.py
> +            datetime(year=2011, month=1, day=1, hour=0, minute=0, second=0, tzinfo=tzutc()))
Done in the next commit

2020-09-08 07:51 UTC, aanersc commented on tests/normalizers/test_url.py
> +            datetime(year=1983, month=1, day=1, hour=0, minute=0, second=0, tzinfo=tzutc()))
Done in the next commit

2020-09-08 08:12 UTC, aanersc commented
@akorosov 
all of your comments are addressed in 87f63ea

2020-09-08 09:03 UTC, aperrin66 requested changes

2020-09-08 09:03 UTC, aperrin66 commented on tests/normalizers/test_url.py
> +        cls.normalizer = normalizers.URLMetadataNormalizer([], [])
Why use this and not a simple `setUp()` method?

2020-09-08 09:20 UTC, aanersc commented on metanorm/normalizers/url.py
> +                file_name.split('_')[0] + '_' +file_name.split('_')[1] if '_' in file_name else None
@aperrin66 
That if in the line 127 causes me to write it in this way! otherwise, there is an error that comes from the cases that the file does not have the '_' inside it!

2020-09-08 09:23 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                file_name.split('_')[0] + '_' +file_name.split('_')[1] if '_' in file_name else None
That does not prevent you from doing the splitting and storing the result in a variable before declaring the dictionary.

2020-09-08 09:32 UTC, aanersc commented on metanorm/normalizers/url.py
> +                url_time, raw_attributes, URLMetadataNormalizer.extract_time)
@aperrin66 
The reason for defining a static method is that these methods are not changing the state of the class or its intrances. This reason is not related to how these methods are intract with other, does it?
All three of find_matching_value, extract_time and find_time_coverage interact with other without modifying the class or instance. Do we have to do it like that?

2020-09-08 09:32 UTC, aanersc commented on metanorm/normalizers/url.py
> +                file_name.split('_')[0] + '_' +file_name.split('_')[1] if '_' in file_name else None
Done in the next commit.

2020-09-08 09:33 UTC, aanersc commented on metanorm/normalizers/url.py
> +                extracted_date += relativedelta(days=int(file_name[1:4])-1)
Done in the next commit

2020-09-08 09:35 UTC, aanersc commented on tests/normalizers/test_url.py
> +        cls.normalizer = normalizers.URLMetadataNormalizer([], [])
@aperrin66 
Because of speed of testing! Since this is a simple normalizer and only works with the sime text(ftp address or url address), I tihnk It is enough to instatnce it once and use the same one and just pass different texts to it and see how things are gonna work in the different tests.

2020-09-08 09:38 UTC, aanersc commented on metanorm/normalizers/url.py
> +        return relativedelta(days=calendar.monthrange(extracted_date.year, extracted_date.month)[1]-1)
Done in the next commit

2020-09-08 09:38 UTC, aanersc commented on metanorm/normalizers/url.py
> +                elif re.search("^f35_......v8\.2\.gz$", file_name):
Done in the next commit

2020-09-08 09:40 UTC, aanersc commented on metanorm/normalizers/url.py
> +                url_time, raw_attributes, URLMetadataNormalizer.extract_time)
@aperrin66 
I am telling it based on this webpage:
https://realpython.com/instance-class-and-static-methods-demystified/

2020-09-08 09:42 UTC, aanersc commented on metanorm/normalizers/url.py
> +                    return desired_function(associated_dict[url])
@aperrin66 
Then what is in your mind? :)

2020-09-08 09:45 UTC, akorosov commented on metanorm/normalizers/url.py
> +                    return desired_function(associated_dict[url])
That was my suggestion. I find it to be a very convenient way to call find_matching_value exactly the same way from all the methods. And then in each `get_` function it is clear which function is used.

2020-09-08 09:51 UTC, akorosov commented on metanorm/normalizers/url.py
> +                url_time, raw_attributes, URLMetadataNormalizer.extract_time)
`find_matching_value` does need access the class or the instance so it can be safely static method. But it is called inconsistently with other places. It is better to call `self. find_matching_value(...` as in the example `return self.circle_area(self.radius)`

2020-09-08 09:57 UTC, aanersc commented on metanorm/normalizers/url.py
> +                url_time, raw_attributes, URLMetadataNormalizer.extract_time)
@aperrin66 
@akorosov 
That `self` is impossible to be written in that line! Unless we convert the `find_time_coverage` function into a class method.Do you want it? 
I don't think it is good for `find_time_coverage` to be a class_method. But the choice is yours.

2020-09-08 10:04 UTC, aanersc commented on metanorm/normalizers/url.py
> +                url_time, raw_attributes, URLMetadataNormalizer.extract_time)
@akorosov 
That call of return self.circle_area(self.radius) is from inside a **class method** not a static method!

I have called a static method inside **another static method**!

2020-09-08 10:05 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                url_time, raw_attributes, URLMetadataNormalizer.extract_time)
Yes I still think it should be a class method

2020-09-08 10:08 UTC, aperrin66 commented on tests/normalizers/test_url.py
> +        cls.normalizer = normalizers.URLMetadataNormalizer([], [])
OK, but keep in mind that this works because the state of the normalizer is not modified in your tests.

2020-09-08 10:13 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                    return desired_function(associated_dict[url])
I think it would be clearer to just return `associated_dict[url]` and call the function in each `get_` method, but it's just my personal preference.

2020-09-08 10:28 UTC, aanersc commented on tests/normalizers/test_url.py
> +        cls.normalizer = normalizers.URLMetadataNormalizer([], [])
Yeap!

2020-09-08 10:31 UTC, aanersc commented on metanorm/normalizers/url.py
> +                    return desired_function(associated_dict[url])
@aperrin66 @akorosov 
So which way?

2020-09-08 10:33 UTC, aanersc commented on metanorm/normalizers/url.py
> +                url_time, raw_attributes, URLMetadataNormalizer.extract_time)
Done in the next commit

2020-09-08 10:48 UTC, aanersc commented
@aperrin66 
@akorosov 
All of your comments are addressed in 20ab33f

2020-09-08 10:59 UTC, akorosov requested changes
Few changes to comply with Adrien's comment on find_matching_value

2020-09-08 10:59 UTC, akorosov commented on metanorm/normalizers/url.py
> +    def find_matching_value(associated_dict, raw_attributes, desired_function):
```suggestion
    def find_matching_value(associated_dict, raw_attributes):
```

2020-09-08 10:59 UTC, akorosov commented on metanorm/normalizers/url.py
> +                    return desired_function(associated_dict[url])
```suggestion
                    return associated_dict[url]
```

2020-09-08 10:59 UTC, akorosov commented on metanorm/normalizers/url.py
> +        """ Loop through <associated_dict> and get the matching value using appropriate function """
```suggestion
        """ Loop through <associated_dict> and get the matching value """
```

2020-09-08 10:59 UTC, akorosov commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_platforms, raw_attributes, pti.get_gcmd_platform)
```suggestion
        return pti.get_gcmd_platform(self.find_matching_value(self.urls_platforms, raw_attributes))
```

2020-09-08 10:59 UTC, akorosov commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_instruments, raw_attributes, pti.get_gcmd_instrument)
```suggestion
        return  pti.get_gcmd_instrument(self.find_matching_value(self.urls_instruments, raw_attributes))
```

2020-09-08 10:59 UTC, akorosov commented on metanorm/normalizers/url.py
> +                url_time, raw_attributes, self.extract_time)
```suggestion
            extracted_date = self.extract_time(self.find_matching_value(
                url_time, raw_attributes))
```

2020-09-08 10:59 UTC, akorosov commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_provider, raw_attributes, pti.get_gcmd_provider)
```suggestion
        return pti.get_gcmd_provider(self.find_matching_value(self.urls_provider, raw_attributes))
```

2020-09-08 10:59 UTC, akorosov commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_dsp, raw_attributes, self.create_parameter_list) or []
```suggestion
        return self.create_parameter_list(self.find_matching_value(self.urls_dsp, raw_attributes)) or []
```

2020-09-08 10:59 UTC, akorosov commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_geometry, raw_attributes, GEOSGeometry)
```suggestion
        return GEOSGeometry(self.find_matching_value(self.urls_geometry, raw_attributes))
```

2020-09-08 10:59 UTC, akorosov commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_title, raw_attributes, str)
```suggestion
        return self.find_matching_value(self.urls_title, raw_attributes)
```

2020-09-08 10:59 UTC, akorosov commented on metanorm/normalizers/url.py
> +
```suggestion
```

2020-09-08 11:21 UTC, akorosov commented on metanorm/normalizers/url.py
> +    def find_time_coverage(self, raw_attributes, start):
Dockstring

2020-09-08 12:33 UTC, aanersc commented
@aanersc 
@akorosov 
Everything is set on 521c264 and 5a5a87f.

2020-09-08 12:34 UTC, aanersc commented on metanorm/normalizers/url.py
> +    def find_time_coverage(self, raw_attributes, start):
Done in the next commit

2020-09-08 12:35 UTC, aanersc commented on metanorm/normalizers/url.py
> +    def find_time_coverage(self, raw_attributes, start):
Done in the next commit

2020-09-08 12:35 UTC, aanersc commented on metanorm/normalizers/url.py
> +
Done in the next commit

2020-09-08 12:35 UTC, aanersc commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_title, raw_attributes, str)
Done in the next commit

2020-09-08 12:35 UTC, aanersc commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_geometry, raw_attributes, GEOSGeometry)
Done in the next commit

2020-09-08 12:35 UTC, aanersc commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_dsp, raw_attributes, self.create_parameter_list) or []
Done in the next commit

2020-09-08 12:35 UTC, aanersc commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_provider, raw_attributes, pti.get_gcmd_provider)
Done in the next commit

2020-09-08 12:35 UTC, aanersc commented on metanorm/normalizers/url.py
> +                url_time, raw_attributes, self.extract_time)
Done in the next commit

2020-09-08 12:35 UTC, aanersc commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_instruments, raw_attributes, pti.get_gcmd_instrument)
Done in the next commit

2020-09-08 12:36 UTC, aanersc commented on metanorm/normalizers/url.py
> +        return self.find_matching_value(self.urls_platforms, raw_attributes, pti.get_gcmd_platform)
Done in the next commit

2020-09-08 12:36 UTC, aanersc commented on metanorm/normalizers/url.py
> +    def find_matching_value(associated_dict, raw_attributes, desired_function):
Done in the next commit

2020-09-08 12:36 UTC, aanersc commented on metanorm/normalizers/url.py
> +                    return desired_function(associated_dict[url])
Done in the next commit

2020-09-08 12:58 UTC, akorosov requested changes
It is not compliant with PEP8:
"The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation."

But a line should not be broken where it is not needed.

2020-09-08 12:58 UTC, akorosov commented on metanorm/normalizers/url.py
> +            relativedelta(days=calendar.monthrange(
```suggestion
        return relativedelta(days=calendar.monthrange(
```

2020-09-08 12:58 UTC, akorosov commented on metanorm/normalizers/url.py
> +            self.create_parameter_list(self.find_matching_value(
Why do you add a backslash here? It saves you only 3 characters. But `return  self.create_parameter_list(self.find_matching_value(` is still well below the limit!

```suggestion
        return self.create_parameter_list(self.find_matching_value(
```

2020-09-08 12:58 UTC, akorosov commented on metanorm/normalizers/url.py
> +            return pti.get_gcmd_platform(founded_values)
Yes, now I remember why I previously suggested to apply a desired_function inside the `find_matching_value`: it doesn't require to use `if` in every `get_` method. Now we are back to repetition. Maybe it is better readable but it is not DRY and the same mistake has to be fixed in several places. For example, `found` instead of `founded`, and `value` instead of `values`, and no comma after the last parameter in every call to `find_matching_value`.

It is up to you how to call find_matching_value but at least fix the variable name and the comma here and everywhere.
```suggestion
        found_value = self.find_matching_value(self.urls_platforms, raw_attributes)
        if found_value:
            return pti.get_gcmd_platform(found_value)
```

2020-09-08 13:16 UTC, aanersc commented on metanorm/normalizers/url.py
> +            self.create_parameter_list(self.find_matching_value(
it is a combination of my correction and autopep8. I have correct it. Done in the next commit.

2020-09-08 13:17 UTC, aanersc commented on metanorm/normalizers/url.py
> +            relativedelta(days=calendar.monthrange(
it is a combination of my correction and autopep8. I have correct it. Done in the next commit.

2020-09-08 13:22 UTC, aanersc commented
@akorosov @aperrin66 
All set in 293aa7b

2020-09-08 13:49 UTC, akorosov approved these changes
Finally :)

2020-09-08 14:28 UTC, aperrin66 requested changes
There is no test for `get_location_geometry()` with a correct URL

2020-09-09 06:16 UTC, aanersc commented
@aperrin66 
@akorosov 
mentioned tests are added in 8a6c3c9

2020-09-09 06:44 UTC, aperrin66 approved these changes

2020-09-09 07:23 UTC, merged