Issue22 entry id config
nansencenter/metanorm pull request #28
Opened 2020-09-10 12:10 UTC by aanersc

2020-09-10 12:14 UTC, aanersc commented
I don't know why but irrelevant commit are also added to this pr. Please, pay attention to the last commit only!!!!

2020-09-10 12:26 UTC, akorosov requested changes
URL-normalizer should also be able to process any url from DDX ingester. With the current implementation it is not possible. Please prepare a solution that works with DDX and discuss with me before further development.

2020-09-10 12:26 UTC, akorosov commented on metanorm/normalizers/url.py
> +            if any(raw_attributes['url'].startswith(key) for key in self.urls_title.keys()):
What if URL come from DDX ingester? Then this will not work. Please prepare a more generic solution and discuss with me before implementing.

2020-09-10 13:00 UTC, aanersc commented
@akorosov 
YOur comment is addressed in ce4da89.

2020-09-10 13:18 UTC, akorosov requested changes
Great! Can you also add examples of files from podaac and osisaf to tests?

2020-09-11 12:47 UTC, akorosov approved these changes

2020-09-11 12:49 UTC, akorosov commented
@aperrin66 , can you have a look? Now metanorm should return entry_id from raw_attributes from all ingesters.

2020-09-14 07:19 UTC, aperrin66 requested changes
There are a few things to change and a few elements to be aware of, otherwise it looks fine.

2020-09-14 07:19 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                file_name = os.path.splitext(os.path.basename(raw_attributes['url']))[0]
`os.path.splitext()` only splits the last extension.
So for a link like those we get from thredds.met.no: 

https://thredds.met.no/thredds/dodsC/osisaf/met.no/ice/drift_mr/2014/07/ice_drift_nh_polstere-200_avhrr-ch2_201407112204_201407122158.nc.dods

We will get the following result: `ice_drift_nh_polstere-200_avhrr-ch2_201407112204_201407122158.nc`

But for a link from PODAAC like this:

https://opendap.jpl.nasa.gov/opendap/allData/ghrsst/data/GDS2/L2P/MODIS_A/JPL/v2019.0/2020/085/20200325000000-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0.nc

We will get `20200325000000-JPL-L2P_GHRSST-SSTskin-MODIS_A-D-v02.0-fv01.0`.

2020-09-14 07:19 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                file_name = os.path.splitext(os.path.basename(raw_attributes['url']))[0]
Although it works, be aware that using `os.path.basename()` on a URL is not what this function was intended for.
You are taking advantage of an undocumented behavior, so it's not guaranteed that it will always work in later versions.
Also, I don't know how that would behave on Windows.

2020-09-14 07:19 UTC, aperrin66 commented on tests/normalizers/test_url.py
> +            'url': "https://thredds.met.no/thredds/catalog/osisaf/Some/path/to/file/filename.bb"}
the download URL would be "https://thredds.met.no/thredds/catalog/osisaf/Some/path/to/file/filename.bb.dods"

2020-09-14 07:34 UTC, aanersc commented on metanorm/normalizers/url.py
> +                return file_name if file_name else None
Done in the next commit.

2020-09-14 07:35 UTC, aanersc commented on tests/normalizers/test_sentinel_safe.py
> +            'Identifier':'finename_value'}
Done in the next commit.

2020-09-14 07:45 UTC, aanersc commented on metanorm/normalizers/url.py
> +                file_name = os.path.splitext(os.path.basename(raw_attributes['url']))[0]
@aperrin66 
SO, how many times should we split? one time for podaac and two times for osisaf?
shall we use another if here?

2020-09-14 07:50 UTC, aanersc commented on metanorm/normalizers/url.py
> +                file_name = os.path.splitext(os.path.basename(raw_attributes['url']))[0]
@aperrin66 
splitext is the suggestion of @akorosov . I would rather use the split method of python. what is your opinion @akorosov ?

2020-09-14 07:52 UTC, aanersc commented on tests/normalizers/test_url.py
> +            'url': "https://thredds.met.no/thredds/catalog/osisaf/Some/path/to/file/filename.bb"}
Done in the next commit.

2020-09-14 07:55 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                file_name = os.path.splitext(os.path.basename(raw_attributes['url']))[0]
This might not even be a problem, I am just raising the point to make sure it has been considered.

2020-09-14 08:04 UTC, aanersc commented on metanorm/normalizers/url.py
> +                file_name = os.path.splitext(os.path.basename(raw_attributes['url']))[0]
@aperrin66 
I have tested that this line is also working:
```python
file_name = os.path.basename(raw_attributes['url']).split('.')[0]
```
which one should I put here? above one or the splitext one?

2020-09-14 09:47 UTC, aanersc commented on metanorm/normalizers/url.py
> +                file_name = os.path.splitext(os.path.basename(raw_attributes['url']))[0]
Done in the next commit.

2020-09-14 09:49 UTC, aanersc commented
@aperrin66 
@akorosov 
Everything except the exclusivity comment is solved in the 1cb465b. If you agreed,it is ready to merge.otherwise....

2020-09-14 10:12 UTC, aanersc commented
@aperrin66
@akorosov
Everything except the exclusivity comment is solved in the be2bb1d. If you agreed,it is ready to merge.otherwise....

2020-09-14 10:24 UTC, aperrin66 requested changes

2020-09-14 10:24 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                    ntpath.split(ntpath.basename(raw_attributes['url']))[0] # for windows users
That won't work for several reasons:
- `os.path.basename()` will return something on Windows, I just wasn't sure how it would treat the `/` characters in the URL since the filesystem separator in Windows is `\`. So your second line is never executed.
- the second line does not do what you want anyway: `ntpath` is the Windows implementation of `os.path`, so it uses `\`, so it won't work on URLs

2020-09-14 10:24 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                    file_name = file_name.replace(ext, '')
That's too specific, please keep one of the two solutions you mentioned before.
`split('.')` is the most generic one here, so I think I'd go with that if @akorosov agrees.

2020-09-14 11:10 UTC, aanersc commented on metanorm/normalizers/url.py
> +                    file_name = file_name.replace(ext, '')
@aperrin66 
`splitext` is actually a one-time `split('.')`!!! nothing more! So, @akorosov shall decide. If we have cases like `blablabla.nc.dods` there is no other than that code to remove the `nc` in the second round of extension removal. This is all related to how frequently we encounter such situation.

2020-09-14 11:13 UTC, aanersc commented on metanorm/normalizers/url.py
> +                    file_name = file_name.replace(ext, '')
@aperrin66 
@akorosov 
something that should be mentioned is that when we use `split('.')` we can't see the rest of the filename if there is a version number specified with '.'. For example, 'f35_20140603v8.2' filename is always being read as 'f35_20140603v8'

2020-09-14 11:18 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                    file_name = file_name.replace(ext, '')
> splitext is actually a one-time split('.')!!! nothing more! 

Not exactly:
- `'blablabla.nc.dods'.split('.')` returns `['blablabla', 'nc', 'dods']`
- `os.path.splitext('blablabla.nc.dods')` returns `('blablabla.nc', '.dods')`

So `file_name.split('.')[0]` will remove all extensions whatever the number, whereas `os.path.splitext(file_name)` only removes the last extension.

2020-09-14 11:26 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                    file_name = file_name.replace(ext, '')
In order to have something that works every time, `urls_entry_id` can be turned into a dictionary in which the URL is the key and the value is a regular expression that can be used to extract the file name (or any part of the URL that we want to use as ID).

2020-09-14 13:42 UTC, aanersc commented
@aanersc 
Your comment is addressed in 793690c.

2020-09-14 13:57 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                     }
No need to use lambdas, just store [compiled regular expressions](https://docs.python.org/3/library/re.html#re.compile) here.

2020-09-14 13:58 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                     }
Just use `search()` instead of `findall()[0]`

2020-09-15 06:11 UTC, aanersc commented on metanorm/normalizers/url.py
> +                     }
Done in the next commit

2020-09-15 06:11 UTC, aanersc commented on metanorm/normalizers/url.py
> +                     }
Done in the next commit

2020-09-15 06:13 UTC, aanersc commented
@aperrin66 
YOur comment is addressed in e7db6e8.

I have also carefully modified the other dictionary of entry_title for the exact assignment of title.

2020-09-15 06:23 UTC, aanersc commented
There is a minor modification in 637f3a5 based on pylint.

2020-09-15 07:10 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                     re.compile(r"^ice_.{39}"),
Using the number of characters is very rigid and will stop working at the slightest change.
You also have the opportunity here to get rid of the problematic `os.path.basename()` call below.

For this particular case, you could use something like `r'([^/]+)\.nc\.dods$'`.

Then, you can apply it to the whole URL in `get_entry_id()` (you will need to use `self.urls_entry_id[url_start].search(...).group(1)` to extract the file name).

2020-09-15 07:10 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                                          os.path.basename(raw_attributes['url'])).group(0)
the regex search needs to be inside a `try` block

2020-09-15 07:56 UTC, aanersc commented
@aperrin66 
coded as you guided in ea1803d.

2020-09-15 07:57 UTC, aanersc commented
@aperrin66 
I have also added the second possible extension that could be in that specific ftp resource.

2020-09-15 07:58 UTC, aanersc commented
@aperrin66 
it seems one more test is needed! based on coverage!

2020-09-15 08:03 UTC, aanersc commented
@aperrin66 
the test is added in 8c45444.

2020-09-15 09:33 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                     "https://opendap.jpl.nasa.gov/opendap/": re.compile(r"([^/]+)\.nc|([^/]+)\.gz"),
No need to repeat the whole pattern: `r"([^/]+)\.(nc|gz)"` does the same thing.
Plus, if there is a `.gz` extension, it's probably not going to be by itself, more likely `.nc.gz`, so this is probably more relevant: `r"([^/]+)\.nc.(gz)?"`
Please fix all the regexes accordingly.

2020-09-15 09:34 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                     re.compile(r"([^/]+)\.nc|([^/]+)\.h5")
Please add a `$` anchor at the end of all these regular expressions.

2020-09-15 09:35 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                        or re.search(self.urls_entry_id[url_start],raw_attributes['url']).group(2)
you can remove the second line once you applied the suggestion of the previous comment

2020-09-15 09:56 UTC, aanersc commented
@aperrin66 
addressed in 40cffc3.

2020-09-17 06:28 UTC, aperrin66 commented on metanorm/normalizers/url.py
> +                            self.urls_entry_id[url_start],raw_attributes['url']).group(1)
The standard way of doing this would be: `self.urls_entry_id[url_start].search(raw_attributes['url']).group(1)`

2020-09-17 06:29 UTC, aperrin66 approved these changes

2020-09-17 11:42 UTC, merged