needed files for aviso and cpom
nansencenter/metanorm pull request #79
Opened 2021-07-27 06:38 UTC by azamifard

2021-07-27 07:40 UTC, aperrin66 requested changes

2021-07-27 07:40 UTC, aperrin66 commented on metanorm/normalizers/CPOM.py
> +            return utils.get_gcmd_instrument('Computer')
I am really not sure that this product is a model.
I will add Anton as reviewer to confirm.

2021-07-27 07:40 UTC, aperrin66 commented on metanorm/normalizers/CPOM.py
> +            return datetime(2014, 12, 31, 23, 59, 59, 999999, tzinfo=timezone.utc)
```suggestion
            return datetime(2015, 1, 1, tzinfo=timezone.utc)
```

2021-07-27 07:40 UTC, aperrin66 commented on metanorm/normalizers/aviso.py
> +import pythesint as pti
unused import

2021-07-27 07:40 UTC, aperrin66 commented on metanorm/normalizers/aviso.py
> +            return utils.get_gcmd_instrument('Computer')
Same as for CPOM altimetry, I am not sure that this product would be considered a model.

2021-07-27 07:40 UTC, aperrin66 commented on metanorm/normalizers/aviso.py
> +            return raw_attributes['title']
I think this can be found by the ACDDMetadataNormalizer

2021-07-27 07:40 UTC, aperrin66 commented on metanorm/normalizers/aviso.py
> +            return utils.get_gcmd_platform('OPERATIONAL MODELS')
There is a platform field in the metadata.

2021-07-27 07:40 UTC, aperrin66 commented on metanorm/normalizers/aviso.py
> +"""Normalizer metadata from netcdf file from aviso"""
This dataset follows the NETCDF_CF and "Unidata Dataset Discovery" conventions, so I think it can be managed without adding a normalizer for just one case.

I left  the comments I made in this file earlier for your information, but I think this new normalizer is not necessary.

2021-07-27 07:40 UTC, aperrin66 commented on metanorm/normalizers/aviso.py
> +            return raw_attributes['title']
The title is "DT multi-satellite sea level gridded product", this is not a good unique value for an entry ID.

2021-07-27 07:45 UTC, azamifard commented on metanorm/normalizers/CPOM.py
> +"""Normalizer metadat from netcdf file from aviso"""
fixed

2021-07-27 07:48 UTC, azamifard commented on metanorm/normalizers/CPOM.py
> +            return datetime(2014, 12, 31, 23, 59, 59, 999999, tzinfo=timezone.utc)
yes, we can do it like your suggestion. I should notice that "for filtering", if we start the filtering time from beginning of 2015, then this file will show up in the result which does not have any 2015 data inside! I will do it your way anyway

2021-07-27 07:49 UTC, azamifard commented on metanorm/normalizers/aviso.py
> +import pythesint as pti
thanks, removed.

2021-07-27 07:58 UTC, azamifard commented on metanorm/normalizers/aviso.py
> +            return raw_attributes['title']
yes, you are right, it can!

2021-07-27 07:58 UTC, azamifard commented on metanorm/normalizers/aviso.py
> +            return raw_attributes['title']
I removed it

2021-07-27 08:06 UTC, azamifard commented on metanorm/normalizers/aviso.py
> +            return utils.get_gcmd_platform('OPERATIONAL MODELS')
I test that, it gives this fields as the reponse of util:
![image](https://user-images.githubusercontent.com/62345618/127119180-21632dbe-cda7-4d81-8efc-a83a1c7a9dc9.png)

which means it cannot find anything. I will do it with your suggestion

2021-07-27 08:06 UTC, azamifard commented on metanorm/normalizers/aviso.py
> +            return utils.get_gcmd_platform('OPERATIONAL MODELS')
Done

2021-07-27 08:10 UTC, aperrin66 commented
One more thing, please add unit tests for the code you add.

2021-07-27 08:13 UTC, azamifard commented on metanorm/normalizers/aviso.py
> +"""Normalizer metadata from netcdf file from aviso"""
No, we can not remove this normalizer, otherwise we receive error during normalization:
![image](https://user-images.githubusercontent.com/62345618/127120141-059a470c-2ed0-4899-90da-77052e7a7938.png)

2021-07-27 08:15 UTC, aperrin66 commented on metanorm/normalizers/aviso.py
> +            return utils.get_gcmd_platform('OPERATIONAL MODELS')
I just realized that these are actually the names of three platforms: SARAL, CryoSat, and Sentinel 3.
We cannot manage multiple platforms in django-geo-spaas.
Maybe there is a proper value for multi-platform products in GCMD?

2021-07-27 08:18 UTC, azamifard commented on metanorm/normalizers/aviso.py
> +            return raw_attributes['title']
OK. I replace it with "dt_arctic_multimission_sea_level_20160701_20190429" which the name of the file and it is unique

2021-07-27 08:20 UTC, aperrin66 commented on metanorm/normalizers/aviso.py
> +"""Normalizer metadata from netcdf file from aviso"""
I did not say that you should just remove that normalizer and it would work.
I meant that it would be better to work with normalizers that are dedicated to a particular convention.
That is how metanorm is supposed to work in the first place. Hard coding and special cases should be a last resort solution.

2021-07-27 09:25 UTC, azamifard commented on metanorm/normalizers/aviso.py
> +            return utils.get_gcmd_platform('OPERATIONAL MODELS')
I have searched the pti as shown below and there is no relevant result in the pti platform list:
![image](https://user-images.githubusercontent.com/62345618/127130390-a3baf4f2-08b0-4acf-9e37-e05eac01c061.png)

so have to use the code as it is.

2021-07-27 11:20 UTC, aperrin66 commented on metanorm/normalizers/aviso.py
> +            return utils.get_gcmd_platform('OPERATIONAL MODELS')
You won't find much by randomly searching like that.
By using the [GCMD keyword viewer](https://gcmd.earthdata.nasa.gov/KeywordViewer/), you can find relevant keywords.
Something like `pti.get_gcmd_platform('OBSERVATION BASED ANALYSES')` would probably work.

2021-07-27 12:18 UTC, azamifard commented
@aperrin66 now with e372d2c, it is ready to review

2021-07-28 06:32 UTC, aperrin66 commented
> @aperrin66 now with [e372d2c](https://github.com/nansencenter/metanorm/commit/e372d2ca1c07e8ff7fd2205dc239b72561d910d3), it is ready to review

[This](https://github.com/nansencenter/metanorm/pull/79/files#r677227595) is not addressed.
Please try to think of a way to do that generically.

2021-08-02 09:37 UTC, aperrin66 approved these changes
Given #81, we can just merge this as it is, it will easily integrate in the new structure.

2021-08-02 11:12 UTC, akorosov requested changes

2021-08-02 11:12 UTC, akorosov commented on metanorm/normalizers/CPOM.py
> +            return utils.get_gcmd_platform('OPERATIONAL MODELS')
```suggestion
            return utils.get_gcmd_platform('Earth Observation Satellites')
```

2021-08-02 11:12 UTC, akorosov commented on metanorm/normalizers/CPOM.py
> +        """ return 'Computer' instrument """
```suggestion
        """ return 'Altimeters' instrument """
```

2021-08-02 11:12 UTC, akorosov commented on metanorm/normalizers/CPOM.py
> +            return utils.get_gcmd_instrument('Computer')
```suggestion
            return utils.get_gcmd_instrument('Altimeters')
```

2021-08-02 11:12 UTC, akorosov commented on metanorm/normalizers/aviso.py
> +        """ return 'OPERATIONAL MODELS' platform """
```suggestion
        """ return 'Earth Observation Satellites' platform """
```

2021-08-02 11:12 UTC, akorosov commented on metanorm/normalizers/aviso.py
> +            return utils.get_gcmd_platform('OBSERVATION BASED ANALYSES')
```suggestion
            return utils.get_gcmd_platform('Earth Observation Satellites')
```

2021-08-02 11:12 UTC, akorosov commented on metanorm/normalizers/aviso.py
> +            return utils.get_gcmd_instrument('Computer')
```suggestion
            return utils.get_gcmd_instrument('Altimeters')
```

2021-08-02 11:12 UTC, akorosov commented on tests/normalizers/test_CPOM.py
> +                         ('Long_Name', '')
```suggestion
            OrderedDict([('Category', 'Earth Observation Satellites'),
                         ('Series_Entity', ''),
                         ('Short_Name', ''),
                         ('Long_Name', '')
```

2021-08-02 11:12 UTC, akorosov commented on tests/normalizers/test_CPOM.py
> +                                     ])
```suggestion
                         OrderedDict([('Category', 'Earth Remote Sensing Instruments'),
                                      ('Class', 'Active Remote Sensing'),
                                      ('Type', 'Altimeters'),
                                      ('Subtype', ''),
                                      ('Short_Name', ''),
                                      ('Long_Name', '')
                                     ])
```

2021-08-02 11:12 UTC, akorosov commented on tests/normalizers/test_aviso.py
> +             ('Long_Name', 'OBSERVATION BASED ANALYSES')]))
```suggestion
            OrderedDict([('Category', 'Earth Observation Satellites'),
             ('Series_Entity', ''),
             ('Short_Name', ''),
             ('Long_Name', '')]))
```

2021-08-02 11:12 UTC, akorosov commented on tests/normalizers/test_aviso.py
> +             ('Long_Name', 'Computer')]))
```suggestion
            OrderedDict([('Category', 'Earth Remote Sensing Instruments'),
             ('Class', 'Active Remote Sensing'),
             ('Type', 'Altimeters'),
             ('Subtype', ''),
             ('Short_Name', ''),
             ('Long_Name', '')]))
```

2021-08-02 12:36 UTC, akorosov approved these changes

2021-08-02 12:36 UTC, merged